[package]
name = "lightshow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.2"
log = "0.4.22"
scrap = "0.5.0"
serialport = "4.5.1"
simplelog = "0.12.2"
